
-- BD CLIENT

CREATE DATABASE bd_client
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
	
	
-- Tabla CLIENTE_PERSONAL
CREATE TABLE TB_PERSONAL_CLIENT (
    INT_ID_CPERSONAL SERIAL PRIMARY KEY NOT NULL,    
    VCH_NAME VARCHAR(255) NOT NULL,
    VCH_SURNAME VARCHAR(255) NOT NULL,    
    VCH_CELLPHONE VARCHAR(50),
    VCH_GENDER VARCHAR(50),
	VCH_ADDRESS VARCHAR(255),
    VCH_EMAIL VARCHAR(50),
	VCH_TYPE_DOCUMENT VARCHAR(50),
	VCH_NUM_DOCUMENT VARCHAR(8) NOT NULL UNIQUE,
    VCH_STATUS VARCHAR(50),
    VCH_USER_CREATION VARCHAR(255),
    VCH_USER_MODIFICATION VARCHAR(255),
    DT_DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_DATE_MODIFICATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP     
);

-- Tabla CLIENTE_BUSINESS
CREATE TABLE TB_BUSINESS_CLIENT (
    INT_ID_CBUSINESS SERIAL PRIMARY KEY NOT NULL,    
    VCH_BUSINESS_NAME VARCHAR(255) NOT NULL,
    VCH_PHONE VARCHAR(50),    
    VCH_HOLDER VARCHAR(255) NOT NULL,
    VCH_ADDRESS VARCHAR(255),
    VCH_EMAIL VARCHAR(50),
	VCH_TYPE_DOCUMENT VARCHAR(50),
	VCH_NUM_DOCUMENT VARCHAR(11) NOT NULL UNIQUE,
    VCH_STATUS VARCHAR(50),
    VCH_USER_CREATION VARCHAR(255),
    VCH_USER_MODIFICATION VARCHAR(255),
    DT_DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_DATE_MODIFICATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
	

SELECT * FROM TB_BUSINESS_CLIENT;




-- BD BANK ACCOUNT

CREATE DATABASE bd_bank_account
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
	
	
	
-- Tabla TB_BANK_ACCOUNT
CREATE TABLE TB_BANK_ACCOUNT (
    INT_ID_BANK_ACCOUNT SERIAL PRIMARY KEY NOT NULL,  
	INT_ID_CLIENT INTEGER NOT NULL,
	INT_ID_TYPE_ACCOUNT INTEGER NOT NULL,
	VCH_NUM_ACCOUNT VARCHAR(255) NOT NULL,
	DOU_OPENING_AMOUNT DECIMAL(20,2),
	DOU_BALANCE DECIMAL(20,2),
	DT_OPENING_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	VCH_STATUS VARCHAR(50),
	VCH_USER_CREATION VARCHAR(255),
    VCH_USER_MODIFICATION VARCHAR(255),
    DT_DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_DATE_MODIFICATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_type_account FOREIGN KEY (INT_ID_TYPE_ACCOUNT) REFERENCES TB_TYPE_ACCOUNT(INT_ID_TYPE_ACCOUNT)

);


-- Tabla TB_TYPE_ACCOUNT
CREATE TABLE TB_TYPE_ACCOUNT (
    INT_ID_TYPE_ACCOUNT SERIAL PRIMARY KEY NOT NULL,
	VCH_ACCOUNT_CODE VARCHAR(10) NOT NULL,
	VCH_ACCOUNT_TYPE_NAME VARCHAR(100) NOT NULL,
	INT_MOVEMENT_LIMIT INTEGER,
	DOU_COMISSION_MANT DECIMAL(20,2)
);

-- INSERT DE TIPO DE CUENTAS A LA TABLA TB_TYPE_ACCOUNT
INSERT INTO TB_TYPE_ACCOUNT (VCH_ACCOUNT_CODE,VCH_ACCOUNT_TYPE_NAME,INT_MOVEMENT_LIMIT,DOU_COMISSION_MANT)
VALUES 
('CA','CUENTA DE AHORRO', 0,0),
('CC','CUENTA CORRIENTE', 0,0),
('PF','PLAZO FIJO', 0,0);



SELECT * FROM TB_BANK_ACCOUNT;
SELECT * FROM TB_TYPE_ACCOUNT;




-- BD TRANSACTION

CREATE DATABASE bd_transaction
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
	
	
-- Tabla TB_TYPE_TRANSACTION
CREATE TABLE TB_TYPE_TRANSACTION (
    INT_ID_TYPE_TRANSACTION SERIAL PRIMARY KEY NOT NULL,    
    VCH_TRANSACTION_CODE VARCHAR(10) NOT NULL,    
    VCH_TRANSACTION_NAME VARCHAR(100) NOT NULL
);

-- Tabla TB_TRANSACTION
CREATE TABLE TB_TRANSACTION (
    INT_ID_TRANSACTION SERIAL PRIMARY KEY NOT NULL,  
    INT_ID_BANK_ACCOUNT INTEGER NOT NULL,
    INT_ID_TYPE_TRANSACTION INTEGER NOT NULL,
    VCH_SENDER_ACCOUNT VARCHAR(255) NOT NULL,
    VCH_DESTINATION_ACCOUNT VARCHAR(255) NOT NULL,
    DOU_AMOUNT DECIMAL(20,2) NOT NULL,
    DT_DATE_OPERATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VCH_USER_CREATION VARCHAR(255) NOT NULL,
    VCH_USER_MODIFICATION VARCHAR(255),
    DT_DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_DATE_MODIFICATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,    
    CONSTRAINT fk_type_transaction FOREIGN KEY (INT_ID_TYPE_TRANSACTION) REFERENCES TB_TYPE_TRANSACTION(INT_ID_TYPE_TRANSACTION)
);


-- INSERT DE TIPO DE TRANSACCION A LA TABLA TB_TYPE_TRANSACTION
INSERT INTO TB_TYPE_TRANSACTION (VCH_TRANSACTION_CODE,VCH_TRANSACTION_NAME)
VALUES 
('DE','DEPÓSITO'),
('RE','RETIROS'),
('CT','CARGO A TARJETA DE CRÉDITO'),
('CS','CONSULTA DE SALDO'),
('MH','MOVIMIENTO HISTÓRICO')



SELECT * FROM TB_TYPE_TRANSACTION;
SELECT * FROM TB_TRANSACTION;




-- BD CREDIT

CREATE DATABASE bd_credit
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
	
-- Tabla TB_TYPE_TRANSACTION
CREATE TABLE TB_TYPE_CREDIT (
    INT_ID_TYPE_CREDIT SERIAL PRIMARY KEY NOT NULL,    
    VCH_CREDIT_CODE VARCHAR(10) NOT NULL,    
    VCH_CREDIT_NAME VARCHAR(100) NOT NULL
);

-- Tabla TB_CREDIT
CREATE TABLE TB_CREDIT (
    INT_ID_CREDIT SERIAL PRIMARY KEY NOT NULL,  
    INT_ID_CLIENT INTEGER NOT NULL,
    INT_ID_TYPE_CREDIT INTEGER NOT NULL,
	DOU_AMOUNT DECIMAL(15,2) NOT NULL,
	DOU_INTERES_RATE DECIMAL(5,2) NOT NULL,
	DT_GRANT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	INT_INSTALLMENTS INTEGER NOT NULL,
	VCH_STATUS VARCHAR(30) NOT NULL,
	CONSTRAINT fk_type_CREDIT FOREIGN KEY (INT_ID_TYPE_CREDIT) REFERENCES TB_TYPE_CREDIT(INT_ID_TYPE_CREDIT)


);
