
spring:
  application:
    name: credit-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bd_credit
    username: postgres
    password: lander
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8004
